apiVersion: dns.ovh.edixos.io/v1alpha1
kind: Name
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/name
  labels:
    testing.upbound.io/example-name: domain
  name: domain
spec:
  forProvider:
    domainName: example.com
    targetSpec:
      dnsConfiguration:
        nameServers:
        - nameServer: dns101.ovh.net
        - nameServer: ns101.ovh.net
