/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DomainAccountInitParameters struct {

	// Name of the email account (without the domain part)
	AccountName *string `json:"accountName,omitempty" tf:"account_name,omitempty"`

	// Description of the email account
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of the email domain
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// Password of the email account
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// Size of the email account in bytes
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`
}

type DomainAccountObservation struct {

	// Name of the email account (without the domain part)
	AccountName *string `json:"accountName,omitempty" tf:"account_name,omitempty"`

	// Description of the email account
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of the email domain
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// Email address of the account
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Whether the account is blocked
	IsBlocked *bool `json:"isBlocked,omitempty" tf:"is_blocked,omitempty"`

	// Size of the email account in bytes
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`
}

type DomainAccountParameters struct {

	// Name of the email account (without the domain part)
	// +kubebuilder:validation:Optional
	AccountName *string `json:"accountName,omitempty" tf:"account_name,omitempty"`

	// Description of the email account
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of the email domain
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// Password of the email account
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.SecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// Size of the email account in bytes
	// +kubebuilder:validation:Optional
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`
}

// DomainAccountSpec defines the desired state of DomainAccount
type DomainAccountSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DomainAccountParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DomainAccountInitParameters `json:"initProvider,omitempty"`
}

// DomainAccountStatus defines the observed state of DomainAccount.
type DomainAccountStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DomainAccountObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DomainAccount is the Schema for the DomainAccounts API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,ovh}
type DomainAccount struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountName) || (has(self.initProvider) && has(self.initProvider.accountName))",message="spec.forProvider.accountName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.domain) || (has(self.initProvider) && has(self.initProvider.domain))",message="spec.forProvider.domain is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.passwordSecretRef)",message="spec.forProvider.passwordSecretRef is a required parameter"
	Spec   DomainAccountSpec   `json:"spec"`
	Status DomainAccountStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DomainAccountList contains a list of DomainAccounts
type DomainAccountList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DomainAccount `json:"items"`
}

// Repository type metadata.
var (
	DomainAccount_Kind             = "DomainAccount"
	DomainAccount_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DomainAccount_Kind}.String()
	DomainAccount_KindAPIVersion   = DomainAccount_Kind + "." + CRDGroupVersion.String()
	DomainAccount_GroupVersionKind = CRDGroupVersion.WithKind(DomainAccount_Kind)
)

func init() {
	SchemeBuilder.Register(&DomainAccount{}, &DomainAccountList{})
}
