//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectNetworkPrivate) DeepCopyInto(out *ProjectNetworkPrivate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectNetworkPrivate.
func (in *ProjectNetworkPrivate) DeepCopy() *ProjectNetworkPrivate {
	if in == nil {
		return nil
	}
	out := new(ProjectNetworkPrivate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectNetworkPrivate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectNetworkPrivateInitParameters) DeepCopyInto(out *ProjectNetworkPrivateInitParameters) {
	*out = *in
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.VlanID != nil {
		in, out := &in.VlanID, &out.VlanID
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectNetworkPrivateInitParameters.
func (in *ProjectNetworkPrivateInitParameters) DeepCopy() *ProjectNetworkPrivateInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectNetworkPrivateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectNetworkPrivateList) DeepCopyInto(out *ProjectNetworkPrivateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProjectNetworkPrivate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectNetworkPrivateList.
func (in *ProjectNetworkPrivateList) DeepCopy() *ProjectNetworkPrivateList {
	if in == nil {
		return nil
	}
	out := new(ProjectNetworkPrivateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectNetworkPrivateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectNetworkPrivateObservation) DeepCopyInto(out *ProjectNetworkPrivateObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RegionsAttributes != nil {
		in, out := &in.RegionsAttributes, &out.RegionsAttributes
		*out = make([]RegionsAttributesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RegionsStatus != nil {
		in, out := &in.RegionsStatus, &out.RegionsStatus
		*out = make([]RegionsStatusObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.VlanID != nil {
		in, out := &in.VlanID, &out.VlanID
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectNetworkPrivateObservation.
func (in *ProjectNetworkPrivateObservation) DeepCopy() *ProjectNetworkPrivateObservation {
	if in == nil {
		return nil
	}
	out := new(ProjectNetworkPrivateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectNetworkPrivateParameters) DeepCopyInto(out *ProjectNetworkPrivateParameters) {
	*out = *in
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.VlanID != nil {
		in, out := &in.VlanID, &out.VlanID
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectNetworkPrivateParameters.
func (in *ProjectNetworkPrivateParameters) DeepCopy() *ProjectNetworkPrivateParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectNetworkPrivateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectNetworkPrivateSpec) DeepCopyInto(out *ProjectNetworkPrivateSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectNetworkPrivateSpec.
func (in *ProjectNetworkPrivateSpec) DeepCopy() *ProjectNetworkPrivateSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectNetworkPrivateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectNetworkPrivateStatus) DeepCopyInto(out *ProjectNetworkPrivateStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectNetworkPrivateStatus.
func (in *ProjectNetworkPrivateStatus) DeepCopy() *ProjectNetworkPrivateStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectNetworkPrivateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionsAttributesInitParameters) DeepCopyInto(out *RegionsAttributesInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionsAttributesInitParameters.
func (in *RegionsAttributesInitParameters) DeepCopy() *RegionsAttributesInitParameters {
	if in == nil {
		return nil
	}
	out := new(RegionsAttributesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionsAttributesObservation) DeepCopyInto(out *RegionsAttributesObservation) {
	*out = *in
	if in.Openstackid != nil {
		in, out := &in.Openstackid, &out.Openstackid
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionsAttributesObservation.
func (in *RegionsAttributesObservation) DeepCopy() *RegionsAttributesObservation {
	if in == nil {
		return nil
	}
	out := new(RegionsAttributesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionsAttributesParameters) DeepCopyInto(out *RegionsAttributesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionsAttributesParameters.
func (in *RegionsAttributesParameters) DeepCopy() *RegionsAttributesParameters {
	if in == nil {
		return nil
	}
	out := new(RegionsAttributesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionsStatusInitParameters) DeepCopyInto(out *RegionsStatusInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionsStatusInitParameters.
func (in *RegionsStatusInitParameters) DeepCopy() *RegionsStatusInitParameters {
	if in == nil {
		return nil
	}
	out := new(RegionsStatusInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionsStatusObservation) DeepCopyInto(out *RegionsStatusObservation) {
	*out = *in
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionsStatusObservation.
func (in *RegionsStatusObservation) DeepCopy() *RegionsStatusObservation {
	if in == nil {
		return nil
	}
	out := new(RegionsStatusObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionsStatusParameters) DeepCopyInto(out *RegionsStatusParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionsStatusParameters.
func (in *RegionsStatusParameters) DeepCopy() *RegionsStatusParameters {
	if in == nil {
		return nil
	}
	out := new(RegionsStatusParameters)
	in.DeepCopyInto(out)
	return out
}
