apiVersion: cloud.ovh.m.edixos.io/v1alpha1
kind: ProjectSSHKey
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/projectsshkey
  labels:
    testing.upbound.io/example-name: key
  name: key
  namespace: upbound-system
spec:
  forProvider:
    name: new_key
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC9xPpdqP3sx2H+gcBm65tJEaUbuifQ1uGkgrWtNY0PRKNNPdy+3yoVOtxk6Vjo4YZ0EU/JhmQfnrK7X7Q5vhqYxmozi0LiTRt0BxgqHJ+4hWTWMIOgr+C2jLx7ZsCReRk+fy5AHr6h0PHQEuXVLXeUy/TDyuY2JPtUZ5jcqvLYgQ==
      my-key
    serviceName: <public cloud project ID>
