apiVersion: cloud.ovh.m.edixos.io/v1alpha1
kind: S3Credentials
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/s3credentials
  labels:
    testing.upbound.io/example-name: my_s3_credentials
  name: my-s3-credentials
  namespace: upbound-system
spec:
  forProvider:
    serviceName: ${ovh_cloud_project_user.user.service_name}
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: user

---

apiVersion: cloud.ovh.m.edixos.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: cloud/v1alpha1/s3credentials
  labels:
    testing.upbound.io/example-name: user
  name: user
  namespace: upbound-system
spec:
  forProvider:
    description: my user for acceptance tests
    roleNames:
    - objectstore_operator
    serviceName: XXX
