/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ProjectDatabaseDatabaseInitParameters struct {

	// Cluster ID.
	// Id of the database cluster
	// +crossplane:generate:reference:type=github.com/edixos/provider-ovh/apis/namespaced/databases/v1alpha1.ProjectDatabase
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ProjectDatabase in databases to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ProjectDatabase in databases to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// The engine of the database cluster you want to add. You can find the complete list of available engine in the public documentation. Available engines:
	// Name of the engine of the service
	Engine *string `json:"engine,omitempty" tf:"engine,omitempty"`

	// Name of the database.
	// Database name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The id of the public cloud project. If omitted, the OVH_CLOUD_PROJECT_SERVICE environment variable is used.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type ProjectDatabaseDatabaseObservation struct {

	// Cluster ID.
	// Id of the database cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Defines if the database has been created by default.
	// Defines if the database has been created by default
	Default *bool `json:"default,omitempty" tf:"default,omitempty"`

	// The engine of the database cluster you want to add. You can find the complete list of available engine in the public documentation. Available engines:
	// Name of the engine of the service
	Engine *string `json:"engine,omitempty" tf:"engine,omitempty"`

	// ID of the database.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the database.
	// Database name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The id of the public cloud project. If omitted, the OVH_CLOUD_PROJECT_SERVICE environment variable is used.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type ProjectDatabaseDatabaseParameters struct {

	// Cluster ID.
	// Id of the database cluster
	// +crossplane:generate:reference:type=github.com/edixos/provider-ovh/apis/namespaced/databases/v1alpha1.ProjectDatabase
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a ProjectDatabase in databases to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v1.NamespacedReference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a ProjectDatabase in databases to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v1.NamespacedSelector `json:"clusterIdSelector,omitempty" tf:"-"`

	// The engine of the database cluster you want to add. You can find the complete list of available engine in the public documentation. Available engines:
	// Name of the engine of the service
	// +kubebuilder:validation:Optional
	Engine *string `json:"engine,omitempty" tf:"engine,omitempty"`

	// Name of the database.
	// Database name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The id of the public cloud project. If omitted, the OVH_CLOUD_PROJECT_SERVICE environment variable is used.
	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

// ProjectDatabaseDatabaseSpec defines the desired state of ProjectDatabaseDatabase
type ProjectDatabaseDatabaseSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ProjectDatabaseDatabaseParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectDatabaseDatabaseInitParameters `json:"initProvider,omitempty"`
}

// ProjectDatabaseDatabaseStatus defines the observed state of ProjectDatabaseDatabase.
type ProjectDatabaseDatabaseStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectDatabaseDatabaseObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProjectDatabaseDatabase is the Schema for the ProjectDatabaseDatabases API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ovh}
type ProjectDatabaseDatabase struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.engine) || (has(self.initProvider) && has(self.initProvider.engine))",message="spec.forProvider.engine is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	Spec   ProjectDatabaseDatabaseSpec   `json:"spec"`
	Status ProjectDatabaseDatabaseStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectDatabaseDatabaseList contains a list of ProjectDatabaseDatabases
type ProjectDatabaseDatabaseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectDatabaseDatabase `json:"items"`
}

// Repository type metadata.
var (
	ProjectDatabaseDatabase_Kind             = "ProjectDatabaseDatabase"
	ProjectDatabaseDatabase_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProjectDatabaseDatabase_Kind}.String()
	ProjectDatabaseDatabase_KindAPIVersion   = ProjectDatabaseDatabase_Kind + "." + CRDGroupVersion.String()
	ProjectDatabaseDatabase_GroupVersionKind = CRDGroupVersion.WithKind(ProjectDatabaseDatabase_Kind)
)

func init() {
	SchemeBuilder.Register(&ProjectDatabaseDatabase{}, &ProjectDatabaseDatabaseList{})
}
