/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type InstanceGroupCurrentStateInitParameters struct {
}

type InstanceGroupCurrentStateLocationInitParameters struct {
}

type InstanceGroupCurrentStateLocationObservation struct {

	// Availability zone
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// Region
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type InstanceGroupCurrentStateLocationParameters struct {
}

type InstanceGroupCurrentStateObservation struct {
	Location *InstanceGroupCurrentStateLocationObservation `json:"location,omitempty" tf:"location,omitempty"`

	Members []MembersObservation `json:"members,omitempty" tf:"members,omitempty"`

	// Instance group name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Placement policy
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`
}

type InstanceGroupCurrentStateParameters struct {
}

type InstanceGroupInitParameters struct {

	// Instance group name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Placement policy applied to the group's member instances (`AFFINITY`, `ANTI_AFFINITY`)
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`

	// Region where the instance group will be created
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Service name of the resource representing the id of the cloud project
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type InstanceGroupObservation struct {

	// Computed hash representing the current target specification value
	Checksum *string `json:"checksum,omitempty" tf:"checksum,omitempty"`

	// Creation date of the instance group
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	CurrentState *InstanceGroupCurrentStateObservation `json:"currentState,omitempty" tf:"current_state,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Instance group name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Placement policy applied to the group's member instances (`AFFINITY`, `ANTI_AFFINITY`)
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`

	// Region where the instance group will be created
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Instance group readiness in the system (`CREATING`, `DELETING`, `ERROR`, `OUT_OF_SYNC`, `READY`)
	ResourceStatus *string `json:"resourceStatus,omitempty" tf:"resource_status,omitempty"`

	// Service name of the resource representing the id of the cloud project
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type InstanceGroupParameters struct {

	// Instance group name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Placement policy applied to the group's member instances (`AFFINITY`, `ANTI_AFFINITY`)
	// +kubebuilder:validation:Optional
	Policy *string `json:"policy,omitempty" tf:"policy,omitempty"`

	// Region where the instance group will be created
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Service name of the resource representing the id of the cloud project
	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type MembersInitParameters struct {
}

type MembersObservation struct {

	// Instance ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type MembersParameters struct {
}

// InstanceGroupSpec defines the desired state of InstanceGroup
type InstanceGroupSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            InstanceGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InstanceGroupInitParameters `json:"initProvider,omitempty"`
}

// InstanceGroupStatus defines the observed state of InstanceGroup.
type InstanceGroupStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InstanceGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// InstanceGroup is the Schema for the InstanceGroups API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ovh}
type InstanceGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.policy) || (has(self.initProvider) && has(self.initProvider.policy))",message="spec.forProvider.policy is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	Spec   InstanceGroupSpec   `json:"spec"`
	Status InstanceGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InstanceGroupList contains a list of InstanceGroups
type InstanceGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InstanceGroup `json:"items"`
}

// Repository type metadata.
var (
	InstanceGroup_Kind             = "InstanceGroup"
	InstanceGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: InstanceGroup_Kind}.String()
	InstanceGroup_KindAPIVersion   = InstanceGroup_Kind + "." + CRDGroupVersion.String()
	InstanceGroup_GroupVersionKind = CRDGroupVersion.WithKind(InstanceGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&InstanceGroup{}, &InstanceGroupList{})
}
