/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ProjectVolumeInitParameters struct {

	// A description of the volume
	// Volume description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// id of the volume
	// Image ID
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// id of the volume
	// Instance ID
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Name of the volume
	// Volume name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Required. A valid OVHcloud public cloud region name in which the volume will be available. Ex.: "GRA11". Changing this value recreates the resource.
	// Region name
	RegionName *string `json:"regionName,omitempty" tf:"region_name,omitempty"`

	// Required. The id of the public cloud project. Changing this value recreates the resource.
	// Service name
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Size (GB) of the volume
	// Volume size
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// id of the volume
	// Snapshot ID
	SnapshotID *string `json:"snapshotId,omitempty" tf:"snapshot_id,omitempty"`

	// Type of the volume Changing this value recreates the resource.
	// Type of the volume
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// id of the volume
	// Volume ID
	VolumeID *string `json:"volumeId,omitempty" tf:"volume_id,omitempty"`
}

type ProjectVolumeObservation struct {

	// The action of the operation
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// The completed date of the operation
	CompletedAt *string `json:"completedAt,omitempty" tf:"completed_at,omitempty"`

	// The creation date of the operation
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// A description of the volume
	// Volume description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// id of the volume
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// id of the volume
	// Image ID
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// id of the volume
	// Instance ID
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Name of the volume
	// Volume name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Volume status
	Progress *float64 `json:"progress,omitempty" tf:"progress,omitempty"`

	// Required. A valid OVHcloud public cloud region name in which the volume will be available. Ex.: "GRA11". Changing this value recreates the resource.
	// Region name
	RegionName *string `json:"regionName,omitempty" tf:"region_name,omitempty"`

	// List of regions
	Regions []*string `json:"regions,omitempty" tf:"regions,omitempty"`

	// id of the volume
	// Id of the resource
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// Required. The id of the public cloud project. Changing this value recreates the resource.
	// Service name
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Size (GB) of the volume
	// Volume size
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// id of the volume
	// Snapshot ID
	SnapshotID *string `json:"snapshotId,omitempty" tf:"snapshot_id,omitempty"`

	// Datetime of the operation creation
	StartedAt *string `json:"startedAt,omitempty" tf:"started_at,omitempty"`

	// Volume status
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	SubOperations []SubOperationsObservation `json:"subOperations,omitempty" tf:"sub_operations,omitempty"`

	// Type of the volume Changing this value recreates the resource.
	// Type of the volume
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// id of the volume
	// Volume ID
	VolumeID *string `json:"volumeId,omitempty" tf:"volume_id,omitempty"`
}

type ProjectVolumeParameters struct {

	// A description of the volume
	// Volume description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// id of the volume
	// Image ID
	// +kubebuilder:validation:Optional
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// id of the volume
	// Instance ID
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Name of the volume
	// Volume name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Required. A valid OVHcloud public cloud region name in which the volume will be available. Ex.: "GRA11". Changing this value recreates the resource.
	// Region name
	// +kubebuilder:validation:Optional
	RegionName *string `json:"regionName,omitempty" tf:"region_name,omitempty"`

	// Required. The id of the public cloud project. Changing this value recreates the resource.
	// Service name
	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Size (GB) of the volume
	// Volume size
	// +kubebuilder:validation:Optional
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// id of the volume
	// Snapshot ID
	// +kubebuilder:validation:Optional
	SnapshotID *string `json:"snapshotId,omitempty" tf:"snapshot_id,omitempty"`

	// Type of the volume Changing this value recreates the resource.
	// Type of the volume
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// id of the volume
	// Volume ID
	// +kubebuilder:validation:Optional
	VolumeID *string `json:"volumeId,omitempty" tf:"volume_id,omitempty"`
}

type SubOperationsInitParameters struct {
}

type SubOperationsObservation struct {

	// id of the volume
	// Affected resource of the sub-operation
	ResourceID *string `json:"resourceId,omitempty" tf:"resource_id,omitempty"`

	// Type of the volume Changing this value recreates the resource.
	// The started date of the sub-operation
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`
}

type SubOperationsParameters struct {
}

// ProjectVolumeSpec defines the desired state of ProjectVolume
type ProjectVolumeSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ProjectVolumeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectVolumeInitParameters `json:"initProvider,omitempty"`
}

// ProjectVolumeStatus defines the observed state of ProjectVolume.
type ProjectVolumeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectVolumeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProjectVolume is the Schema for the ProjectVolumes API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ovh}
type ProjectVolume struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.regionName) || (has(self.initProvider) && has(self.initProvider.regionName))",message="spec.forProvider.regionName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	Spec   ProjectVolumeSpec   `json:"spec"`
	Status ProjectVolumeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectVolumeList contains a list of ProjectVolumes
type ProjectVolumeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectVolume `json:"items"`
}

// Repository type metadata.
var (
	ProjectVolume_Kind             = "ProjectVolume"
	ProjectVolume_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProjectVolume_Kind}.String()
	ProjectVolume_KindAPIVersion   = ProjectVolume_Kind + "." + CRDGroupVersion.String()
	ProjectVolume_GroupVersionKind = CRDGroupVersion.WithKind(ProjectVolume_Kind)
)

func init() {
	SchemeBuilder.Register(&ProjectVolume{}, &ProjectVolumeList{})
}
