/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ProjectContainerregistryIAMInitParameters struct {

	// Delete existing users from Harbor. IAM can't be enabled if there is at least one user already created. This parameter is only used at IAM configuration creation. Changing this value recreates the resource.
	DeleteUsers *bool `json:"deleteUsers,omitempty" tf:"delete_users,omitempty"`

	// The ID of the Managed Private Registry. Changing this value recreates the resource.
	RegistryID *string `json:"registryId,omitempty" tf:"registry_id,omitempty"`

	// The ID of the public cloud project. If omitted, the OVH_CLOUD_PROJECT_SERVICE environment variable is used. Changing this value recreates the resource.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type ProjectContainerregistryIAMObservation struct {

	// Delete existing users from Harbor. IAM can't be enabled if there is at least one user already created. This parameter is only used at IAM configuration creation. Changing this value recreates the resource.
	DeleteUsers *bool `json:"deleteUsers,omitempty" tf:"delete_users,omitempty"`

	IAMEnabled *bool `json:"iamEnabled,omitempty" tf:"iam_enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the Managed Private Registry. Changing this value recreates the resource.
	RegistryID *string `json:"registryId,omitempty" tf:"registry_id,omitempty"`

	// The ID of the public cloud project. If omitted, the OVH_CLOUD_PROJECT_SERVICE environment variable is used. Changing this value recreates the resource.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type ProjectContainerregistryIAMParameters struct {

	// Delete existing users from Harbor. IAM can't be enabled if there is at least one user already created. This parameter is only used at IAM configuration creation. Changing this value recreates the resource.
	// +kubebuilder:validation:Optional
	DeleteUsers *bool `json:"deleteUsers,omitempty" tf:"delete_users,omitempty"`

	// The ID of the Managed Private Registry. Changing this value recreates the resource.
	// +kubebuilder:validation:Optional
	RegistryID *string `json:"registryId,omitempty" tf:"registry_id,omitempty"`

	// The ID of the public cloud project. If omitted, the OVH_CLOUD_PROJECT_SERVICE environment variable is used. Changing this value recreates the resource.
	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

// ProjectContainerregistryIAMSpec defines the desired state of ProjectContainerregistryIAM
type ProjectContainerregistryIAMSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ProjectContainerregistryIAMParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectContainerregistryIAMInitParameters `json:"initProvider,omitempty"`
}

// ProjectContainerregistryIAMStatus defines the observed state of ProjectContainerregistryIAM.
type ProjectContainerregistryIAMStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectContainerregistryIAMObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProjectContainerregistryIAM is the Schema for the ProjectContainerregistryIAMs API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ovh}
type ProjectContainerregistryIAM struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.registryId) || (has(self.initProvider) && has(self.initProvider.registryId))",message="spec.forProvider.registryId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	Spec   ProjectContainerregistryIAMSpec   `json:"spec"`
	Status ProjectContainerregistryIAMStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectContainerregistryIAMList contains a list of ProjectContainerregistryIAMs
type ProjectContainerregistryIAMList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectContainerregistryIAM `json:"items"`
}

// Repository type metadata.
var (
	ProjectContainerregistryIAM_Kind             = "ProjectContainerregistryIAM"
	ProjectContainerregistryIAM_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProjectContainerregistryIAM_Kind}.String()
	ProjectContainerregistryIAM_KindAPIVersion   = ProjectContainerregistryIAM_Kind + "." + CRDGroupVersion.String()
	ProjectContainerregistryIAM_GroupVersionKind = CRDGroupVersion.WithKind(ProjectContainerregistryIAM_Kind)
)

func init() {
	SchemeBuilder.Register(&ProjectContainerregistryIAM{}, &ProjectContainerregistryIAMList{})
}
