apiVersion: kms.ovh.m.edixos.io/v1alpha1
kind: Credential
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1alpha1/credential
  labels:
    testing.upbound.io/example-name: cred_no_csr
  name: cred-no-csr
  namespace: upbound-system
spec:
  forProvider:
    certificateType: ECDSA
    description: Credential without CSR
    identityUrns:
    - urn:v1:eu:identity:account:${data.ovh_me.current_account.nichandle}
    name: cred
    okmsId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
