/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ProjectDatabaseMongodbPrometheusInitParameters struct {

	// Cluster ID.
	// Id of the database cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Arbitrary string to change to trigger a password update.
	// Arbitrary string to change to trigger a password update
	PasswordReset *string `json:"passwordReset,omitempty" tf:"password_reset,omitempty"`

	// The id of the public cloud project. If omitted, the OVH_CLOUD_PROJECT_SERVICE environment variable is used.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type ProjectDatabaseMongodbPrometheusObservation struct {

	// Cluster ID.
	// Id of the database cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Cluster ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Arbitrary string to change to trigger a password update.
	// Arbitrary string to change to trigger a password update
	PasswordReset *string `json:"passwordReset,omitempty" tf:"password_reset,omitempty"`

	// The id of the public cloud project. If omitted, the OVH_CLOUD_PROJECT_SERVICE environment variable is used.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Name of the srv domain endpoint.
	// Name of the srv domain endpoint
	SrvDomain *string `json:"srvDomain,omitempty" tf:"srv_domain,omitempty"`

	// name of the prometheus user.
	// Name of the user
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ProjectDatabaseMongodbPrometheusParameters struct {

	// Cluster ID.
	// Id of the database cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Arbitrary string to change to trigger a password update.
	// Arbitrary string to change to trigger a password update
	// +kubebuilder:validation:Optional
	PasswordReset *string `json:"passwordReset,omitempty" tf:"password_reset,omitempty"`

	// The id of the public cloud project. If omitted, the OVH_CLOUD_PROJECT_SERVICE environment variable is used.
	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

// ProjectDatabaseMongodbPrometheusSpec defines the desired state of ProjectDatabaseMongodbPrometheus
type ProjectDatabaseMongodbPrometheusSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProjectDatabaseMongodbPrometheusParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectDatabaseMongodbPrometheusInitParameters `json:"initProvider,omitempty"`
}

// ProjectDatabaseMongodbPrometheusStatus defines the observed state of ProjectDatabaseMongodbPrometheus.
type ProjectDatabaseMongodbPrometheusStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectDatabaseMongodbPrometheusObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProjectDatabaseMongodbPrometheus is the Schema for the ProjectDatabaseMongodbPrometheuss API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,ovh}
type ProjectDatabaseMongodbPrometheus struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clusterId) || (has(self.initProvider) && has(self.initProvider.clusterId))",message="spec.forProvider.clusterId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	Spec   ProjectDatabaseMongodbPrometheusSpec   `json:"spec"`
	Status ProjectDatabaseMongodbPrometheusStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectDatabaseMongodbPrometheusList contains a list of ProjectDatabaseMongodbPrometheuss
type ProjectDatabaseMongodbPrometheusList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectDatabaseMongodbPrometheus `json:"items"`
}

// Repository type metadata.
var (
	ProjectDatabaseMongodbPrometheus_Kind             = "ProjectDatabaseMongodbPrometheus"
	ProjectDatabaseMongodbPrometheus_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProjectDatabaseMongodbPrometheus_Kind}.String()
	ProjectDatabaseMongodbPrometheus_KindAPIVersion   = ProjectDatabaseMongodbPrometheus_Kind + "." + CRDGroupVersion.String()
	ProjectDatabaseMongodbPrometheus_GroupVersionKind = CRDGroupVersion.WithKind(ProjectDatabaseMongodbPrometheus_Kind)
)

func init() {
	SchemeBuilder.Register(&ProjectDatabaseMongodbPrometheus{}, &ProjectDatabaseMongodbPrometheusList{})
}
