apiVersion: cloud.ovh.edixos.io/v1alpha1
kind: S3Policy
metadata:
  name: s3-user-credentials
spec:
  providerConfigRef:
    name: default
  forProvider:
    serviceName: 980cbcf06e6a4e6e8a91a7d125b26bba
    userIdRef:
      name: s3-user
    policy: |
      {
          "Statement":[{
            "Sid": "RWContainer",
            "Effect": "Allow",
            "Action":["s3:GetObject", "s3:PutObject", "s3:DeleteObject", "s3:ListBucket", "s3:ListMultipartUploadParts", "s3:ListBucketMultipartUploads", "s3:AbortMultipartUpload", "s3:GetBucketLocation"],
            "Resource":["arn:aws:s3:::hp-bucket", "arn:aws:s3:::hp-bucket/*"]
          }]
      }
