apiVersion: ovh.edixos.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: ovh-creds
      namespace: crossplane-system
      key: credentials


