apiVersion: dns.ovh.m.edixos.io/v1alpha1
kind: ZoneDNSSEC
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/zonednssec
  labels:
    testing.upbound.io/example-name: dnssec
  name: dnssec
  namespace: upbound-system
spec:
  forProvider:
    zoneName: mysite.ovh
