/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type IploadbalancingInitParameters struct {

	// The id of the IP Load Balancing.
	// Your ipLoadbalancing
	IPLoadbalancing *string `json:"ipLoadbalancing,omitempty" tf:"ip_loadbalancing,omitempty"`

	// The id of the vrack.
	// The internal name of your vrack
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type IploadbalancingObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The id of the IP Load Balancing.
	// Your ipLoadbalancing
	IPLoadbalancing *string `json:"ipLoadbalancing,omitempty" tf:"ip_loadbalancing,omitempty"`

	// The id of the vrack.
	// The internal name of your vrack
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type IploadbalancingParameters struct {

	// The id of the IP Load Balancing.
	// Your ipLoadbalancing
	// +kubebuilder:validation:Optional
	IPLoadbalancing *string `json:"ipLoadbalancing,omitempty" tf:"ip_loadbalancing,omitempty"`

	// The id of the vrack.
	// The internal name of your vrack
	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

// IploadbalancingSpec defines the desired state of Iploadbalancing
type IploadbalancingSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IploadbalancingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IploadbalancingInitParameters `json:"initProvider,omitempty"`
}

// IploadbalancingStatus defines the observed state of Iploadbalancing.
type IploadbalancingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IploadbalancingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Iploadbalancing is the Schema for the Iploadbalancings API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,ovh}
type Iploadbalancing struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ipLoadbalancing) || (has(self.initProvider) && has(self.initProvider.ipLoadbalancing))",message="spec.forProvider.ipLoadbalancing is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	Spec   IploadbalancingSpec   `json:"spec"`
	Status IploadbalancingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IploadbalancingList contains a list of Iploadbalancings
type IploadbalancingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Iploadbalancing `json:"items"`
}

// Repository type metadata.
var (
	Iploadbalancing_Kind             = "Iploadbalancing"
	Iploadbalancing_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Iploadbalancing_Kind}.String()
	Iploadbalancing_KindAPIVersion   = Iploadbalancing_Kind + "." + CRDGroupVersion.String()
	Iploadbalancing_GroupVersionKind = CRDGroupVersion.WithKind(Iploadbalancing_Kind)
)

func init() {
	SchemeBuilder.Register(&Iploadbalancing{}, &IploadbalancingList{})
}
