/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type UserInitParameters struct {

	// User description.
	// User description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// User's email.
	// User's email
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// User's group.
	// User's group
	// +crossplane:generate:reference:type=github.com/edixos/provider-ovh/apis/namespaced/me/v1alpha1.Group
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// Reference to a Group in me to populate group.
	// +kubebuilder:validation:Optional
	GroupRef *v1.NamespacedReference `json:"groupRef,omitempty" tf:"-"`

	// Selector for a Group in me to populate group.
	// +kubebuilder:validation:Optional
	GroupSelector *v1.NamespacedSelector `json:"groupSelector,omitempty" tf:"-"`

	// User's login suffix.
	// User's login suffix
	Login *string `json:"login,omitempty" tf:"login,omitempty"`

	// User's password.
	// User's password
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`
}

type UserObservation struct {

	// Creation date of this user.
	// Creation date of this user
	Creation *string `json:"creation,omitempty" tf:"creation,omitempty"`

	// User description.
	// User description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// User's email.
	// User's email
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// User's group.
	// User's group
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Last update of this user.
	// Last update of this user
	LastUpdate *string `json:"lastUpdate,omitempty" tf:"last_update,omitempty"`

	// User's login suffix.
	// User's login suffix
	Login *string `json:"login,omitempty" tf:"login,omitempty"`

	// When the user changed his password for the last time.
	// When the user changed his password for the last time
	PasswordLastUpdate *string `json:"passwordLastUpdate,omitempty" tf:"password_last_update,omitempty"`

	// Current user's status.
	// Current user's status
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// URN of the user, used when writing IAM policies
	Urn *string `json:"urn,omitempty" tf:"urn,omitempty"`
}

type UserParameters struct {

	// User description.
	// User description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// User's email.
	// User's email
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// User's group.
	// User's group
	// +crossplane:generate:reference:type=github.com/edixos/provider-ovh/apis/namespaced/me/v1alpha1.Group
	// +kubebuilder:validation:Optional
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// Reference to a Group in me to populate group.
	// +kubebuilder:validation:Optional
	GroupRef *v1.NamespacedReference `json:"groupRef,omitempty" tf:"-"`

	// Selector for a Group in me to populate group.
	// +kubebuilder:validation:Optional
	GroupSelector *v1.NamespacedSelector `json:"groupSelector,omitempty" tf:"-"`

	// User's login suffix.
	// User's login suffix
	// +kubebuilder:validation:Optional
	Login *string `json:"login,omitempty" tf:"login,omitempty"`

	// User's password.
	// User's password
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`
}

// UserSpec defines the desired state of User
type UserSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            UserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserInitParameters `json:"initProvider,omitempty"`
}

// UserStatus defines the observed state of User.
type UserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// User is the Schema for the Users API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ovh}
type User struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.email) || (has(self.initProvider) && has(self.initProvider.email))",message="spec.forProvider.email is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.login) || (has(self.initProvider) && has(self.initProvider.login))",message="spec.forProvider.login is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.passwordSecretRef)",message="spec.forProvider.passwordSecretRef is a required parameter"
	Spec   UserSpec   `json:"spec"`
	Status UserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserList contains a list of Users
type UserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []User `json:"items"`
}

// Repository type metadata.
var (
	User_Kind             = "User"
	User_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: User_Kind}.String()
	User_KindAPIVersion   = User_Kind + "." + CRDGroupVersion.String()
	User_GroupVersionKind = CRDGroupVersion.WithKind(User_Kind)
)

func init() {
	SchemeBuilder.Register(&User{}, &UserList{})
}
