/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *ContainerRegistry) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ContainerRegistryIPRestrictionsManagement) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ContainerRegistryIPRestrictionsRegistry) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ContainerRegistryOIDC) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ContainerRegistryUser) Hub() {}
