/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Privatedatabase) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PrivatedatabaseDatabase) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PrivatedatabaseUser) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PrivatedatabaseUserGrant) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PrivatedatabaseWhitelist) Hub() {}
