/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ProjectDatabaseIntegrationInitParameters struct {

	// Id of the database cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// ID of the destination service
	DestinationServiceID *string `json:"destinationServiceId,omitempty" tf:"destination_service_id,omitempty"`

	// Name of the engine of the service
	Engine *string `json:"engine,omitempty" tf:"engine,omitempty"`

	// Parameters for the integration
	// +mapType=granular
	Parameters map[string]*string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// ID of the source service
	SourceServiceID *string `json:"sourceServiceId,omitempty" tf:"source_service_id,omitempty"`

	// Type of the integration
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ProjectDatabaseIntegrationObservation struct {

	// Id of the database cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// ID of the destination service
	DestinationServiceID *string `json:"destinationServiceId,omitempty" tf:"destination_service_id,omitempty"`

	// Name of the engine of the service
	Engine *string `json:"engine,omitempty" tf:"engine,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Parameters for the integration
	// +mapType=granular
	Parameters map[string]*string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// ID of the source service
	SourceServiceID *string `json:"sourceServiceId,omitempty" tf:"source_service_id,omitempty"`

	// Current status of the integration
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Type of the integration
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ProjectDatabaseIntegrationParameters struct {

	// Id of the database cluster
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// ID of the destination service
	// +kubebuilder:validation:Optional
	DestinationServiceID *string `json:"destinationServiceId,omitempty" tf:"destination_service_id,omitempty"`

	// Name of the engine of the service
	// +kubebuilder:validation:Optional
	Engine *string `json:"engine,omitempty" tf:"engine,omitempty"`

	// Parameters for the integration
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Parameters map[string]*string `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// ID of the source service
	// +kubebuilder:validation:Optional
	SourceServiceID *string `json:"sourceServiceId,omitempty" tf:"source_service_id,omitempty"`

	// Type of the integration
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ProjectDatabaseIntegrationSpec defines the desired state of ProjectDatabaseIntegration
type ProjectDatabaseIntegrationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProjectDatabaseIntegrationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectDatabaseIntegrationInitParameters `json:"initProvider,omitempty"`
}

// ProjectDatabaseIntegrationStatus defines the observed state of ProjectDatabaseIntegration.
type ProjectDatabaseIntegrationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectDatabaseIntegrationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProjectDatabaseIntegration is the Schema for the ProjectDatabaseIntegrations API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,lb}
type ProjectDatabaseIntegration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clusterId) || (has(self.initProvider) && has(self.initProvider.clusterId))",message="spec.forProvider.clusterId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.destinationServiceId) || (has(self.initProvider) && has(self.initProvider.destinationServiceId))",message="spec.forProvider.destinationServiceId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.engine) || (has(self.initProvider) && has(self.initProvider.engine))",message="spec.forProvider.engine is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sourceServiceId) || (has(self.initProvider) && has(self.initProvider.sourceServiceId))",message="spec.forProvider.sourceServiceId is a required parameter"
	Spec   ProjectDatabaseIntegrationSpec   `json:"spec"`
	Status ProjectDatabaseIntegrationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectDatabaseIntegrationList contains a list of ProjectDatabaseIntegrations
type ProjectDatabaseIntegrationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProjectDatabaseIntegration `json:"items"`
}

// Repository type metadata.
var (
	ProjectDatabaseIntegration_Kind             = "ProjectDatabaseIntegration"
	ProjectDatabaseIntegration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProjectDatabaseIntegration_Kind}.String()
	ProjectDatabaseIntegration_KindAPIVersion   = ProjectDatabaseIntegration_Kind + "." + CRDGroupVersion.String()
	ProjectDatabaseIntegration_GroupVersionKind = CRDGroupVersion.WithKind(ProjectDatabaseIntegration_Kind)
)

func init() {
	SchemeBuilder.Register(&ProjectDatabaseIntegration{}, &ProjectDatabaseIntegrationList{})
}
