/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *HTTPFarm) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HTTPFarmServer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HTTPFrontend) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HTTPRoute) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *HTTPRouteRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Iploadbalancing) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectRegionLoadbalancerLogSubscription) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Refresh) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SSL) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TCPFarm) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TCPFarmServer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TCPFrontend) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TCPRoute) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TCPRouteRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UDPFarm) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UDPFarmServer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UDPFrontend) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VrackNetwork) Hub() {}
