/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type HTTPFrontendInitParameters struct {

	// Restrict IP Load Balancing access to these ip block. No restriction if null. List of IP blocks.
	// +listType=set
	AllowedSource []*string `json:"allowedSource,omitempty" tf:"allowed_source,omitempty"`

	// Only attach frontend on these ip. No restriction if null. List of Ip blocks.
	// +listType=set
	DedicatedIpfo []*string `json:"dedicatedIpfo,omitempty" tf:"dedicated_ipfo,omitempty"`

	// Default TCP Farm of your frontend
	DefaultFarmID *float64 `json:"defaultFarmId,omitempty" tf:"default_farm_id,omitempty"`

	// Default ssl served to your customer
	DefaultSSLID *float64 `json:"defaultSslId,omitempty" tf:"default_ssl_id,omitempty"`

	// Disable your frontend. Default: 'false'
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// Human readable name for your frontend, this field is for you
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// HTTP headers to add to the frontend. List of string.
	HTTPHeader []*string `json:"httpHeader,omitempty" tf:"http_header,omitempty"`

	// HTTP Strict Transport Security. Default: 'false'
	Hsts *bool `json:"hsts,omitempty" tf:"hsts,omitempty"`

	// Port(s) attached to your frontend. Supports single port (numerical value), range (2 dash-delimited increasing ports) and comma-separated list of 'single port' and/or 'range'. Each port must be in the [1;49151] range
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// Redirection HTTP'
	RedirectLocation *string `json:"redirectLocation,omitempty" tf:"redirect_location,omitempty"`

	// SSL deciphering. Default: 'false'
	SSL *bool `json:"ssl,omitempty" tf:"ssl,omitempty"`

	// The internal name of your IP load balancing
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Zone where the frontend will be defined (ie. gra, bhs also supports all)
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type HTTPFrontendObservation struct {

	// Restrict IP Load Balancing access to these ip block. No restriction if null. List of IP blocks.
	// +listType=set
	AllowedSource []*string `json:"allowedSource,omitempty" tf:"allowed_source,omitempty"`

	// Only attach frontend on these ip. No restriction if null. List of Ip blocks.
	// +listType=set
	DedicatedIpfo []*string `json:"dedicatedIpfo,omitempty" tf:"dedicated_ipfo,omitempty"`

	// Default TCP Farm of your frontend
	DefaultFarmID *float64 `json:"defaultFarmId,omitempty" tf:"default_farm_id,omitempty"`

	// Default ssl served to your customer
	DefaultSSLID *float64 `json:"defaultSslId,omitempty" tf:"default_ssl_id,omitempty"`

	// Disable your frontend. Default: 'false'
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// Human readable name for your frontend, this field is for you
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// HTTP headers to add to the frontend. List of string.
	HTTPHeader []*string `json:"httpHeader,omitempty" tf:"http_header,omitempty"`

	// HTTP Strict Transport Security. Default: 'false'
	Hsts *bool `json:"hsts,omitempty" tf:"hsts,omitempty"`

	// Id of your frontend
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Port(s) attached to your frontend. Supports single port (numerical value), range (2 dash-delimited increasing ports) and comma-separated list of 'single port' and/or 'range'. Each port must be in the [1;49151] range
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// Redirection HTTP'
	RedirectLocation *string `json:"redirectLocation,omitempty" tf:"redirect_location,omitempty"`

	// SSL deciphering. Default: 'false'
	SSL *bool `json:"ssl,omitempty" tf:"ssl,omitempty"`

	// The internal name of your IP load balancing
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Zone where the frontend will be defined (ie. gra, bhs also supports all)
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type HTTPFrontendParameters struct {

	// Restrict IP Load Balancing access to these ip block. No restriction if null. List of IP blocks.
	// +kubebuilder:validation:Optional
	// +listType=set
	AllowedSource []*string `json:"allowedSource,omitempty" tf:"allowed_source,omitempty"`

	// Only attach frontend on these ip. No restriction if null. List of Ip blocks.
	// +kubebuilder:validation:Optional
	// +listType=set
	DedicatedIpfo []*string `json:"dedicatedIpfo,omitempty" tf:"dedicated_ipfo,omitempty"`

	// Default TCP Farm of your frontend
	// +kubebuilder:validation:Optional
	DefaultFarmID *float64 `json:"defaultFarmId,omitempty" tf:"default_farm_id,omitempty"`

	// Default ssl served to your customer
	// +kubebuilder:validation:Optional
	DefaultSSLID *float64 `json:"defaultSslId,omitempty" tf:"default_ssl_id,omitempty"`

	// Disable your frontend. Default: 'false'
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// Human readable name for your frontend, this field is for you
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// HTTP headers to add to the frontend. List of string.
	// +kubebuilder:validation:Optional
	HTTPHeader []*string `json:"httpHeader,omitempty" tf:"http_header,omitempty"`

	// HTTP Strict Transport Security. Default: 'false'
	// +kubebuilder:validation:Optional
	Hsts *bool `json:"hsts,omitempty" tf:"hsts,omitempty"`

	// Port(s) attached to your frontend. Supports single port (numerical value), range (2 dash-delimited increasing ports) and comma-separated list of 'single port' and/or 'range'. Each port must be in the [1;49151] range
	// +kubebuilder:validation:Optional
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// Redirection HTTP'
	// +kubebuilder:validation:Optional
	RedirectLocation *string `json:"redirectLocation,omitempty" tf:"redirect_location,omitempty"`

	// SSL deciphering. Default: 'false'
	// +kubebuilder:validation:Optional
	SSL *bool `json:"ssl,omitempty" tf:"ssl,omitempty"`

	// The internal name of your IP load balancing
	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Zone where the frontend will be defined (ie. gra, bhs also supports all)
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

// HTTPFrontendSpec defines the desired state of HTTPFrontend
type HTTPFrontendSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            HTTPFrontendParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider HTTPFrontendInitParameters `json:"initProvider,omitempty"`
}

// HTTPFrontendStatus defines the observed state of HTTPFrontend.
type HTTPFrontendStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        HTTPFrontendObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// HTTPFrontend is the Schema for the HTTPFrontends API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ovh}
type HTTPFrontend struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.port) || (has(self.initProvider) && has(self.initProvider.port))",message="spec.forProvider.port is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   HTTPFrontendSpec   `json:"spec"`
	Status HTTPFrontendStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// HTTPFrontendList contains a list of HTTPFrontends
type HTTPFrontendList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []HTTPFrontend `json:"items"`
}

// Repository type metadata.
var (
	HTTPFrontend_Kind             = "HTTPFrontend"
	HTTPFrontend_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: HTTPFrontend_Kind}.String()
	HTTPFrontend_KindAPIVersion   = HTTPFrontend_Kind + "." + CRDGroupVersion.String()
	HTTPFrontend_GroupVersionKind = CRDGroupVersion.WithKind(HTTPFrontend_Kind)
)

func init() {
	SchemeBuilder.Register(&HTTPFrontend{}, &HTTPFrontendList{})
}
