/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ConnectPopDatacenterConfigInitParameters struct {

	// (Number) ID of the pop configuration
	// ID of the pop configuration
	ConfigPopID *float64 `json:"configPopId,omitempty" tf:"config_pop_id,omitempty"`

	// (Number) ID of the datacenter linked
	// ID of the datacenter linked
	DatacenterID *float64 `json:"datacenterId,omitempty" tf:"datacenter_id,omitempty"`

	// (Number) OVH Private AS
	// OVH Private AS
	OvhBGPArea *float64 `json:"ovhBgpArea,omitempty" tf:"ovh_bgp_area,omitempty"`

	// (String) Service name
	// Service name
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// (String) Subnet should be a /28 min
	// Subnet should be a /28 min
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`
}

type ConnectPopDatacenterConfigObservation struct {

	// (Number) ID of the pop configuration
	// ID of the pop configuration
	ConfigPopID *float64 `json:"configPopId,omitempty" tf:"config_pop_id,omitempty"`

	// (Number) ID of the datacenter linked
	// ID of the datacenter linked
	DatacenterID *float64 `json:"datacenterId,omitempty" tf:"datacenter_id,omitempty"`

	// (Number) ID of the Datacenter configuration
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) OVH Private AS
	// OVH Private AS
	OvhBGPArea *float64 `json:"ovhBgpArea,omitempty" tf:"ovh_bgp_area,omitempty"`

	// (String) Service name
	// Service name
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// (String) Status of the pop configuration
	// Status of the pop configuration
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) Subnet should be a /28 min
	// Subnet should be a /28 min
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`
}

type ConnectPopDatacenterConfigParameters struct {

	// (Number) ID of the pop configuration
	// ID of the pop configuration
	// +kubebuilder:validation:Optional
	ConfigPopID *float64 `json:"configPopId,omitempty" tf:"config_pop_id,omitempty"`

	// (Number) ID of the datacenter linked
	// ID of the datacenter linked
	// +kubebuilder:validation:Optional
	DatacenterID *float64 `json:"datacenterId,omitempty" tf:"datacenter_id,omitempty"`

	// (Number) OVH Private AS
	// OVH Private AS
	// +kubebuilder:validation:Optional
	OvhBGPArea *float64 `json:"ovhBgpArea,omitempty" tf:"ovh_bgp_area,omitempty"`

	// (String) Service name
	// Service name
	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// (String) Subnet should be a /28 min
	// Subnet should be a /28 min
	// +kubebuilder:validation:Optional
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`
}

// ConnectPopDatacenterConfigSpec defines the desired state of ConnectPopDatacenterConfig
type ConnectPopDatacenterConfigSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ConnectPopDatacenterConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConnectPopDatacenterConfigInitParameters `json:"initProvider,omitempty"`
}

// ConnectPopDatacenterConfigStatus defines the observed state of ConnectPopDatacenterConfig.
type ConnectPopDatacenterConfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ConnectPopDatacenterConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ConnectPopDatacenterConfig is the Schema for the ConnectPopDatacenterConfigs API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ovh}
type ConnectPopDatacenterConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.configPopId) || (has(self.initProvider) && has(self.initProvider.configPopId))",message="spec.forProvider.configPopId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.datacenterId) || (has(self.initProvider) && has(self.initProvider.datacenterId))",message="spec.forProvider.datacenterId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	Spec   ConnectPopDatacenterConfigSpec   `json:"spec"`
	Status ConnectPopDatacenterConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConnectPopDatacenterConfigList contains a list of ConnectPopDatacenterConfigs
type ConnectPopDatacenterConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ConnectPopDatacenterConfig `json:"items"`
}

// Repository type metadata.
var (
	ConnectPopDatacenterConfig_Kind             = "ConnectPopDatacenterConfig"
	ConnectPopDatacenterConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ConnectPopDatacenterConfig_Kind}.String()
	ConnectPopDatacenterConfig_KindAPIVersion   = ConnectPopDatacenterConfig_Kind + "." + CRDGroupVersion.String()
	ConnectPopDatacenterConfig_GroupVersionKind = CRDGroupVersion.WithKind(ConnectPopDatacenterConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&ConnectPopDatacenterConfig{}, &ConnectPopDatacenterConfigList{})
}
