/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AvailabilityZonesInitParameters struct {

	// Availability zone name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Unique priority value [1..3]
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`
}

type AvailabilityZonesObservation struct {

	// Availability zone name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Unique priority value [1..3]
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`
}

type AvailabilityZonesParameters struct {

	// Availability zone name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Unique priority value [1..3]
	// +kubebuilder:validation:Optional
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`
}

type PublicRoutingPriorityInitParameters struct {
	AvailabilityZones []AvailabilityZonesInitParameters `json:"availabilityZones,omitempty" tf:"availability_zones,omitempty"`

	// Name of the region where Public routing priority is defined
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The internal name of your vrack
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type PublicRoutingPriorityObservation struct {
	AvailabilityZones []AvailabilityZonesObservation `json:"availabilityZones,omitempty" tf:"availability_zones,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Public routing priority identifier
	PriorityID *string `json:"priorityId,omitempty" tf:"priority_id,omitempty"`

	// Name of the region where Public routing priority is defined
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The internal name of your vrack
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Public routing priority type
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// vrack name
	Vrack *string `json:"vrack,omitempty" tf:"vrack,omitempty"`
}

type PublicRoutingPriorityParameters struct {

	// +kubebuilder:validation:Optional
	AvailabilityZones []AvailabilityZonesParameters `json:"availabilityZones,omitempty" tf:"availability_zones,omitempty"`

	// Name of the region where Public routing priority is defined
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The internal name of your vrack
	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

// PublicRoutingPrioritySpec defines the desired state of PublicRoutingPriority
type PublicRoutingPrioritySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PublicRoutingPriorityParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PublicRoutingPriorityInitParameters `json:"initProvider,omitempty"`
}

// PublicRoutingPriorityStatus defines the observed state of PublicRoutingPriority.
type PublicRoutingPriorityStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PublicRoutingPriorityObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PublicRoutingPriority is the Schema for the PublicRoutingPrioritys API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ovh}
type PublicRoutingPriority struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.availabilityZones) || (has(self.initProvider) && has(self.initProvider.availabilityZones))",message="spec.forProvider.availabilityZones is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	Spec   PublicRoutingPrioritySpec   `json:"spec"`
	Status PublicRoutingPriorityStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PublicRoutingPriorityList contains a list of PublicRoutingPrioritys
type PublicRoutingPriorityList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PublicRoutingPriority `json:"items"`
}

// Repository type metadata.
var (
	PublicRoutingPriority_Kind             = "PublicRoutingPriority"
	PublicRoutingPriority_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PublicRoutingPriority_Kind}.String()
	PublicRoutingPriority_KindAPIVersion   = PublicRoutingPriority_Kind + "." + CRDGroupVersion.String()
	PublicRoutingPriority_GroupVersionKind = CRDGroupVersion.WithKind(PublicRoutingPriority_Kind)
)

func init() {
	SchemeBuilder.Register(&PublicRoutingPriority{}, &PublicRoutingPriorityList{})
}
