/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AllocationPoolsInitParameters struct {
	End *string `json:"end,omitempty" tf:"end,omitempty"`

	Start *string `json:"start,omitempty" tf:"start,omitempty"`
}

type AllocationPoolsObservation struct {
	End *string `json:"end,omitempty" tf:"end,omitempty"`

	Start *string `json:"start,omitempty" tf:"start,omitempty"`
}

type AllocationPoolsParameters struct {

	// +kubebuilder:validation:Optional
	End *string `json:"end" tf:"end,omitempty"`

	// +kubebuilder:validation:Optional
	Start *string `json:"start" tf:"start,omitempty"`
}

type HostRouteInitParameters struct {
	Destination *string `json:"destination,omitempty" tf:"destination,omitempty"`

	Nexthop *string `json:"nexthop,omitempty" tf:"nexthop,omitempty"`
}

type HostRouteObservation struct {
	Destination *string `json:"destination,omitempty" tf:"destination,omitempty"`

	Nexthop *string `json:"nexthop,omitempty" tf:"nexthop,omitempty"`
}

type HostRouteParameters struct {

	// +kubebuilder:validation:Optional
	Destination *string `json:"destination" tf:"destination,omitempty"`

	// +kubebuilder:validation:Optional
	Nexthop *string `json:"nexthop" tf:"nexthop,omitempty"`
}

type SubnetV2InitParameters struct {

	// List of IP allocation pools Changing this value recreates the resource.
	// DHCP allocation pools of subnet
	AllocationPools []AllocationPoolsInitParameters `json:"allocationPools,omitempty" tf:"allocation_pools,omitempty"`

	// IP range of the subnet Changing this value recreates the subnet.
	// CIDR of subnet
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// Enable DHCP. Changing this forces a new resource to be created. Defaults to true.
	// Enable DHCP in subnet
	DHCP *bool `json:"dhcp,omitempty" tf:"dhcp,omitempty"`

	// DNS nameservers used by DHCP Changing this value recreates the resource. Defaults to OVH default DNS nameserver.
	// List of DNS nameservers, default: 213.186.33.99
	DNSNameservers []*string `json:"dnsNameservers,omitempty" tf:"dns_nameservers,omitempty"`

	// Set to true if you want to set a default gateway IP. Changing this value recreates the resource. Defaults to true.
	// Enable gateway IP in subnet
	EnableGatewayIP *bool `json:"enableGatewayIp,omitempty" tf:"enable_gateway_ip,omitempty"`

	// See Argument Reference above.
	// Gateway IP of subnet
	GatewayIP *string `json:"gatewayIp,omitempty" tf:"gateway_ip,omitempty"`

	// List of custom host routes. Changing this value recreates the resource.
	// Static host routes of subnet
	HostRoute []HostRouteInitParameters `json:"hostRoute,omitempty" tf:"host_route,omitempty"`

	// Name of the subnet Changing this value recreates the subnet.
	// Name of subnet
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The id of the network. Changing this forces a new resource to be created.
	// Network ID of subnet
	// +crossplane:generate:reference:type=github.com/edixos/provider-ovh/apis/cluster/network/v1alpha1.PrivateNetwork
	// +crossplane:generate:reference:extractor=github.com/edixos/provider-ovh/config/common.PrivateNetworkOpenStackIdExtractor()
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a PrivateNetwork in network to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.Reference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a PrivateNetwork in network to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.Selector `json:"networkIdSelector,omitempty" tf:"-"`

	// The region in which the network subnet will be created. Ex.: "GRA1". Changing this value recreates the resource.
	// Region of network/subnet
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The id of the public cloud project. If omitted, the OVH_CLOUD_PROJECT_SERVICE environment variable is used.
	// Service name of the resource representing the id of the cloud project.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Set to false if you want to use your DNS resolver. Changing this value recreates the resource.
	// Use OVH default DNS
	UseDefaultPublicDNSResolver *bool `json:"useDefaultPublicDnsResolver,omitempty" tf:"use_default_public_dns_resolver,omitempty"`
}

type SubnetV2Observation struct {

	// List of IP allocation pools Changing this value recreates the resource.
	// DHCP allocation pools of subnet
	AllocationPools []AllocationPoolsObservation `json:"allocationPools,omitempty" tf:"allocation_pools,omitempty"`

	// IP range of the subnet Changing this value recreates the subnet.
	// CIDR of subnet
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// Enable DHCP. Changing this forces a new resource to be created. Defaults to true.
	// Enable DHCP in subnet
	DHCP *bool `json:"dhcp,omitempty" tf:"dhcp,omitempty"`

	// DNS nameservers used by DHCP Changing this value recreates the resource. Defaults to OVH default DNS nameserver.
	// List of DNS nameservers, default: 213.186.33.99
	DNSNameservers []*string `json:"dnsNameservers,omitempty" tf:"dns_nameservers,omitempty"`

	// Set to true if you want to set a default gateway IP. Changing this value recreates the resource. Defaults to true.
	// Enable gateway IP in subnet
	EnableGatewayIP *bool `json:"enableGatewayIp,omitempty" tf:"enable_gateway_ip,omitempty"`

	// See Argument Reference above.
	// Gateway IP of subnet
	GatewayIP *string `json:"gatewayIp,omitempty" tf:"gateway_ip,omitempty"`

	// List of custom host routes. Changing this value recreates the resource.
	// Static host routes of subnet
	HostRoute []HostRouteObservation `json:"hostRoute,omitempty" tf:"host_route,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the subnet Changing this value recreates the subnet.
	// Name of subnet
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The id of the network. Changing this forces a new resource to be created.
	// Network ID of subnet
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// The region in which the network subnet will be created. Ex.: "GRA1". Changing this value recreates the resource.
	// Region of network/subnet
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The id of the public cloud project. If omitted, the OVH_CLOUD_PROJECT_SERVICE environment variable is used.
	// Service name of the resource representing the id of the cloud project.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Set to false if you want to use your DNS resolver. Changing this value recreates the resource.
	// Use OVH default DNS
	UseDefaultPublicDNSResolver *bool `json:"useDefaultPublicDnsResolver,omitempty" tf:"use_default_public_dns_resolver,omitempty"`
}

type SubnetV2Parameters struct {

	// List of IP allocation pools Changing this value recreates the resource.
	// DHCP allocation pools of subnet
	// +kubebuilder:validation:Optional
	AllocationPools []AllocationPoolsParameters `json:"allocationPools,omitempty" tf:"allocation_pools,omitempty"`

	// IP range of the subnet Changing this value recreates the subnet.
	// CIDR of subnet
	// +kubebuilder:validation:Optional
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// Enable DHCP. Changing this forces a new resource to be created. Defaults to true.
	// Enable DHCP in subnet
	// +kubebuilder:validation:Optional
	DHCP *bool `json:"dhcp,omitempty" tf:"dhcp,omitempty"`

	// DNS nameservers used by DHCP Changing this value recreates the resource. Defaults to OVH default DNS nameserver.
	// List of DNS nameservers, default: 213.186.33.99
	// +kubebuilder:validation:Optional
	DNSNameservers []*string `json:"dnsNameservers,omitempty" tf:"dns_nameservers,omitempty"`

	// Set to true if you want to set a default gateway IP. Changing this value recreates the resource. Defaults to true.
	// Enable gateway IP in subnet
	// +kubebuilder:validation:Optional
	EnableGatewayIP *bool `json:"enableGatewayIp,omitempty" tf:"enable_gateway_ip,omitempty"`

	// See Argument Reference above.
	// Gateway IP of subnet
	// +kubebuilder:validation:Optional
	GatewayIP *string `json:"gatewayIp,omitempty" tf:"gateway_ip,omitempty"`

	// List of custom host routes. Changing this value recreates the resource.
	// Static host routes of subnet
	// +kubebuilder:validation:Optional
	HostRoute []HostRouteParameters `json:"hostRoute,omitempty" tf:"host_route,omitempty"`

	// Name of the subnet Changing this value recreates the subnet.
	// Name of subnet
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The id of the network. Changing this forces a new resource to be created.
	// Network ID of subnet
	// +crossplane:generate:reference:type=github.com/edixos/provider-ovh/apis/cluster/network/v1alpha1.PrivateNetwork
	// +crossplane:generate:reference:extractor=github.com/edixos/provider-ovh/config/common.PrivateNetworkOpenStackIdExtractor()
	// +kubebuilder:validation:Optional
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a PrivateNetwork in network to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.Reference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a PrivateNetwork in network to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.Selector `json:"networkIdSelector,omitempty" tf:"-"`

	// The region in which the network subnet will be created. Ex.: "GRA1". Changing this value recreates the resource.
	// Region of network/subnet
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The id of the public cloud project. If omitted, the OVH_CLOUD_PROJECT_SERVICE environment variable is used.
	// Service name of the resource representing the id of the cloud project.
	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Set to false if you want to use your DNS resolver. Changing this value recreates the resource.
	// Use OVH default DNS
	// +kubebuilder:validation:Optional
	UseDefaultPublicDNSResolver *bool `json:"useDefaultPublicDnsResolver,omitempty" tf:"use_default_public_dns_resolver,omitempty"`
}

// SubnetV2Spec defines the desired state of SubnetV2
type SubnetV2Spec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SubnetV2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SubnetV2InitParameters `json:"initProvider,omitempty"`
}

// SubnetV2Status defines the observed state of SubnetV2.
type SubnetV2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SubnetV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SubnetV2 is the Schema for the SubnetV2s API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,ovh}
type SubnetV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.cidr) || (has(self.initProvider) && has(self.initProvider.cidr))",message="spec.forProvider.cidr is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	Spec   SubnetV2Spec   `json:"spec"`
	Status SubnetV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SubnetV2List contains a list of SubnetV2s
type SubnetV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SubnetV2 `json:"items"`
}

// Repository type metadata.
var (
	SubnetV2_Kind             = "SubnetV2"
	SubnetV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SubnetV2_Kind}.String()
	SubnetV2_KindAPIVersion   = SubnetV2_Kind + "." + CRDGroupVersion.String()
	SubnetV2_GroupVersionKind = CRDGroupVersion.WithKind(SubnetV2_Kind)
)

func init() {
	SchemeBuilder.Register(&SubnetV2{}, &SubnetV2List{})
}
