/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type LogsEncryptionKeyInitParameters struct {

	// PGP public key content
	ContentSecretRef v1.SecretKeySelector `json:"contentSecretRef" tf:"-"`

	// PGP key fingerprint
	Fingerprint *string `json:"fingerprint,omitempty" tf:"fingerprint,omitempty"`

	// Service name
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Encryption key title
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type LogsEncryptionKeyObservation struct {

	// Encryption key creation date
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Encryption key ID
	EncryptionKeyID *string `json:"encryptionKeyId,omitempty" tf:"encryption_key_id,omitempty"`

	// PGP key fingerprint
	Fingerprint *string `json:"fingerprint,omitempty" tf:"fingerprint,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Indicates if the key is editable
	IsEditable *bool `json:"isEditable,omitempty" tf:"is_editable,omitempty"`

	// Service name
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Encryption key title
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type LogsEncryptionKeyParameters struct {

	// PGP public key content
	// +kubebuilder:validation:Optional
	ContentSecretRef v1.SecretKeySelector `json:"contentSecretRef" tf:"-"`

	// PGP key fingerprint
	// +kubebuilder:validation:Optional
	Fingerprint *string `json:"fingerprint,omitempty" tf:"fingerprint,omitempty"`

	// Service name
	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Encryption key title
	// +kubebuilder:validation:Optional
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

// LogsEncryptionKeySpec defines the desired state of LogsEncryptionKey
type LogsEncryptionKeySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     LogsEncryptionKeyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LogsEncryptionKeyInitParameters `json:"initProvider,omitempty"`
}

// LogsEncryptionKeyStatus defines the observed state of LogsEncryptionKey.
type LogsEncryptionKeyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LogsEncryptionKeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LogsEncryptionKey is the Schema for the LogsEncryptionKeys API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,ovh}
type LogsEncryptionKey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.contentSecretRef)",message="spec.forProvider.contentSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.fingerprint) || (has(self.initProvider) && has(self.initProvider.fingerprint))",message="spec.forProvider.fingerprint is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.title) || (has(self.initProvider) && has(self.initProvider.title))",message="spec.forProvider.title is a required parameter"
	Spec   LogsEncryptionKeySpec   `json:"spec"`
	Status LogsEncryptionKeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LogsEncryptionKeyList contains a list of LogsEncryptionKeys
type LogsEncryptionKeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LogsEncryptionKey `json:"items"`
}

// Repository type metadata.
var (
	LogsEncryptionKey_Kind             = "LogsEncryptionKey"
	LogsEncryptionKey_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LogsEncryptionKey_Kind}.String()
	LogsEncryptionKey_KindAPIVersion   = LogsEncryptionKey_Kind + "." + CRDGroupVersion.String()
	LogsEncryptionKey_GroupVersionKind = CRDGroupVersion.WithKind(LogsEncryptionKey_Kind)
)

func init() {
	SchemeBuilder.Register(&LogsEncryptionKey{}, &LogsEncryptionKeyList{})
}
