/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AttachedInstancesInitParameters struct {
}

type AttachedInstancesObservation struct {

	// Identifier of the attached instance
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type AttachedInstancesParameters struct {
}

type BlockVolumeEncryptionInitParameters struct {

	// Whether the volume is encrypted at rest with LUKS
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type BlockVolumeEncryptionObservation struct {

	// Whether the volume is encrypted at rest with LUKS
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type BlockVolumeEncryptionParameters struct {

	// Whether the volume is encrypted at rest with LUKS
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type BlockVolumeInitParameters struct {
	CreateFrom *CreateFromInitParameters `json:"createFrom,omitempty" tf:"create_from,omitempty"`

	Encryption *BlockVolumeEncryptionInitParameters `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// Volume name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Region where the volume will be created
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Service name of the resource representing the id of the cloud project. If omitted, the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Size of the volume in GB
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// Volume type (`CLASSIC`, `HIGH_SPEED`, `HIGH_SPEED_GEN2`). Can be changed after creation (triggers online retype).
	VolumeType *string `json:"volumeType,omitempty" tf:"volume_type,omitempty"`
}

type BlockVolumeObservation struct {

	// Computed hash representing the current target specification value
	Checksum *string `json:"checksum,omitempty" tf:"checksum,omitempty"`

	CreateFrom *CreateFromObservation `json:"createFrom,omitempty" tf:"create_from,omitempty"`

	// Creation date of the volume
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	CurrentState *CurrentStateObservation `json:"currentState,omitempty" tf:"current_state,omitempty"`

	Encryption *BlockVolumeEncryptionObservation `json:"encryption,omitempty" tf:"encryption,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Volume name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Region where the volume will be created
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Volume readiness in the system (CREATING, DELETING, ERROR, OUT_OF_SYNC, READY, UPDATING)
	ResourceStatus *string `json:"resourceStatus,omitempty" tf:"resource_status,omitempty"`

	// Service name of the resource representing the id of the cloud project. If omitted, the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Size of the volume in GB
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// Last update date of the volume
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// Volume type (`CLASSIC`, `HIGH_SPEED`, `HIGH_SPEED_GEN2`). Can be changed after creation (triggers online retype).
	VolumeType *string `json:"volumeType,omitempty" tf:"volume_type,omitempty"`
}

type BlockVolumeParameters struct {

	// +kubebuilder:validation:Optional
	CreateFrom *CreateFromParameters `json:"createFrom,omitempty" tf:"create_from,omitempty"`

	// +kubebuilder:validation:Optional
	Encryption *BlockVolumeEncryptionParameters `json:"encryption,omitempty" tf:"encryption,omitempty"`

	// Volume name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Region where the volume will be created
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Service name of the resource representing the id of the cloud project. If omitted, the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// Size of the volume in GB
	// +kubebuilder:validation:Optional
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// Volume type (`CLASSIC`, `HIGH_SPEED`, `HIGH_SPEED_GEN2`). Can be changed after creation (triggers online retype).
	// +kubebuilder:validation:Optional
	VolumeType *string `json:"volumeType,omitempty" tf:"volume_type,omitempty"`
}

type CreateFromInitParameters struct {

	// Identifier of a backup to restore the volume from
	BackupID *string `json:"backupId,omitempty" tf:"backup_id,omitempty"`

	// UUID of a Glance image to create the volume from. The resulting volume will be bootable. `volumeType` is required when using this field.
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// Identifier of a snapshot to create the volume from
	SnapshotID *string `json:"snapshotId,omitempty" tf:"snapshot_id,omitempty"`
}

type CreateFromObservation struct {

	// Identifier of a backup to restore the volume from
	BackupID *string `json:"backupId,omitempty" tf:"backup_id,omitempty"`

	// UUID of a Glance image to create the volume from. The resulting volume will be bootable. `volumeType` is required when using this field.
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// Identifier of a snapshot to create the volume from
	SnapshotID *string `json:"snapshotId,omitempty" tf:"snapshot_id,omitempty"`
}

type CreateFromParameters struct {

	// Identifier of a backup to restore the volume from
	// +kubebuilder:validation:Optional
	BackupID *string `json:"backupId,omitempty" tf:"backup_id,omitempty"`

	// UUID of a Glance image to create the volume from. The resulting volume will be bootable. `volumeType` is required when using this field.
	// +kubebuilder:validation:Optional
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// Identifier of a snapshot to create the volume from
	// +kubebuilder:validation:Optional
	SnapshotID *string `json:"snapshotId,omitempty" tf:"snapshot_id,omitempty"`
}

type CurrentStateInitParameters struct {
}

type CurrentStateObservation struct {
	AttachedInstances []AttachedInstancesObservation `json:"attachedInstances,omitempty" tf:"attached_instances,omitempty"`

	// Whether the volume is bootable
	Bootable *bool `json:"bootable,omitempty" tf:"bootable,omitempty"`

	Encryption *EncryptionObservation `json:"encryption,omitempty" tf:"encryption,omitempty"`

	Location *LocationObservation `json:"location,omitempty" tf:"location,omitempty"`

	// Volume name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Size of the volume in GB
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// Volume status (`AVAILABLE`, `IN_USE`, `CREATING`, `DELETING`, `ATTACHING`, `DETACHING`, `EXTENDING`, `ERROR`, `ERROR_DELETING`, `ERROR_BACKING_UP`, `ERROR_RESTORING`, `ERROR_EXTENDING`)
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Volume type (`CLASSIC`, `HIGH_SPEED`, `HIGH_SPEED_GEN2`)
	VolumeType *string `json:"volumeType,omitempty" tf:"volume_type,omitempty"`
}

type CurrentStateParameters struct {
}

type EncryptionInitParameters struct {
}

type EncryptionObservation struct {

	// Whether the volume is encrypted at rest with LUKS
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type EncryptionParameters struct {
}

type LocationInitParameters struct {
}

type LocationObservation struct {

	// Region
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type LocationParameters struct {
}

// BlockVolumeSpec defines the desired state of BlockVolume
type BlockVolumeSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BlockVolumeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BlockVolumeInitParameters `json:"initProvider,omitempty"`
}

// BlockVolumeStatus defines the observed state of BlockVolume.
type BlockVolumeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BlockVolumeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BlockVolume is the Schema for the BlockVolumes API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ovh}
type BlockVolume struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.size) || (has(self.initProvider) && has(self.initProvider.size))",message="spec.forProvider.size is a required parameter"
	Spec   BlockVolumeSpec   `json:"spec"`
	Status BlockVolumeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BlockVolumeList contains a list of BlockVolumes
type BlockVolumeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BlockVolume `json:"items"`
}

// Repository type metadata.
var (
	BlockVolume_Kind             = "BlockVolume"
	BlockVolume_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BlockVolume_Kind}.String()
	BlockVolume_KindAPIVersion   = BlockVolume_Kind + "." + CRDGroupVersion.String()
	BlockVolume_GroupVersionKind = CRDGroupVersion.WithKind(BlockVolume_Kind)
)

func init() {
	SchemeBuilder.Register(&BlockVolume{}, &BlockVolumeList{})
}
