/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type FileShareSnapshotCurrentStateInitParameters struct {
}

type FileShareSnapshotCurrentStateLocationInitParameters struct {
}

type FileShareSnapshotCurrentStateLocationObservation struct {

	// Availability zone
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// Region
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type FileShareSnapshotCurrentStateLocationParameters struct {
}

type FileShareSnapshotCurrentStateObservation struct {

	// Snapshot description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Location *FileShareSnapshotCurrentStateLocationObservation `json:"location,omitempty" tf:"location,omitempty"`

	// Snapshot name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ID of the snapshotted file share
	ShareID *string `json:"shareId,omitempty" tf:"share_id,omitempty"`

	// Size of the snapshot in GB
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`
}

type FileShareSnapshotCurrentStateParameters struct {
}

type FileShareSnapshotInitParameters struct {

	// Snapshot description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Snapshot name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Service name of the resource representing the id of the cloud project
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// ID of the file share to snapshot
	// +crossplane:generate:reference:type=github.com/edixos/provider-ovh/apis/namespaced/storage/v1alpha1.FileShare
	ShareID *string `json:"shareId,omitempty" tf:"share_id,omitempty"`

	// Reference to a FileShare in storage to populate shareId.
	// +kubebuilder:validation:Optional
	ShareIDRef *v1.NamespacedReference `json:"shareIdRef,omitempty" tf:"-"`

	// Selector for a FileShare in storage to populate shareId.
	// +kubebuilder:validation:Optional
	ShareIDSelector *v1.NamespacedSelector `json:"shareIdSelector,omitempty" tf:"-"`
}

type FileShareSnapshotObservation struct {

	// Computed hash representing the current target specification value
	Checksum *string `json:"checksum,omitempty" tf:"checksum,omitempty"`

	// Creation date of the snapshot
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	CurrentState *FileShareSnapshotCurrentStateObservation `json:"currentState,omitempty" tf:"current_state,omitempty"`

	// Snapshot description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Snapshot name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Snapshot readiness in the system (CREATING, DELETING, ERROR, OUT_OF_SYNC, READY, UPDATING)
	ResourceStatus *string `json:"resourceStatus,omitempty" tf:"resource_status,omitempty"`

	// Service name of the resource representing the id of the cloud project
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// ID of the file share to snapshot
	ShareID *string `json:"shareId,omitempty" tf:"share_id,omitempty"`

	// Last update date of the snapshot
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type FileShareSnapshotParameters struct {

	// Snapshot description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Snapshot name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Service name of the resource representing the id of the cloud project
	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// ID of the file share to snapshot
	// +crossplane:generate:reference:type=github.com/edixos/provider-ovh/apis/namespaced/storage/v1alpha1.FileShare
	// +kubebuilder:validation:Optional
	ShareID *string `json:"shareId,omitempty" tf:"share_id,omitempty"`

	// Reference to a FileShare in storage to populate shareId.
	// +kubebuilder:validation:Optional
	ShareIDRef *v1.NamespacedReference `json:"shareIdRef,omitempty" tf:"-"`

	// Selector for a FileShare in storage to populate shareId.
	// +kubebuilder:validation:Optional
	ShareIDSelector *v1.NamespacedSelector `json:"shareIdSelector,omitempty" tf:"-"`
}

// FileShareSnapshotSpec defines the desired state of FileShareSnapshot
type FileShareSnapshotSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FileShareSnapshotParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FileShareSnapshotInitParameters `json:"initProvider,omitempty"`
}

// FileShareSnapshotStatus defines the observed state of FileShareSnapshot.
type FileShareSnapshotStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FileShareSnapshotObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FileShareSnapshot is the Schema for the FileShareSnapshots API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ovh}
type FileShareSnapshot struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	Spec   FileShareSnapshotSpec   `json:"spec"`
	Status FileShareSnapshotStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FileShareSnapshotList contains a list of FileShareSnapshots
type FileShareSnapshotList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FileShareSnapshot `json:"items"`
}

// Repository type metadata.
var (
	FileShareSnapshot_Kind             = "FileShareSnapshot"
	FileShareSnapshot_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FileShareSnapshot_Kind}.String()
	FileShareSnapshot_KindAPIVersion   = FileShareSnapshot_Kind + "." + CRDGroupVersion.String()
	FileShareSnapshot_GroupVersionKind = CRDGroupVersion.WithKind(FileShareSnapshot_Kind)
)

func init() {
	SchemeBuilder.Register(&FileShareSnapshot{}, &FileShareSnapshotList{})
}
