/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AccessRulesInitParameters struct {

	// Access level (`READ_WRITE`, `READ_ONLY`)
	AccessLevel *string `json:"accessLevel,omitempty" tf:"access_level,omitempty"`

	// IP address or CIDR to grant access to
	AccessTo *string `json:"accessTo,omitempty" tf:"access_to,omitempty"`
}

type AccessRulesObservation struct {

	// Access level (`READ_WRITE`, `READ_ONLY`)
	AccessLevel *string `json:"accessLevel,omitempty" tf:"access_level,omitempty"`

	// IP address or CIDR to grant access to
	AccessTo *string `json:"accessTo,omitempty" tf:"access_to,omitempty"`
}

type AccessRulesParameters struct {

	// Access level (`READ_WRITE`, `READ_ONLY`)
	// +kubebuilder:validation:Optional
	AccessLevel *string `json:"accessLevel" tf:"access_level,omitempty"`

	// IP address or CIDR to grant access to
	// +kubebuilder:validation:Optional
	AccessTo *string `json:"accessTo" tf:"access_to,omitempty"`
}

type CapabilitiesInitParameters struct {
}

type CapabilitiesObservation struct {

	// Whether the capability is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Capability name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Reason why the capability is disabled
	Reason *string `json:"reason,omitempty" tf:"reason,omitempty"`
}

type CapabilitiesParameters struct {
}

type CurrentStateAccessRulesInitParameters struct {
}

type CurrentStateAccessRulesObservation struct {

	// Access level
	AccessLevel *string `json:"accessLevel,omitempty" tf:"access_level,omitempty"`

	// IP address or CIDR
	AccessTo *string `json:"accessTo,omitempty" tf:"access_to,omitempty"`

	// Access rule creation date
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Access rule ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Access rule state
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type CurrentStateAccessRulesParameters struct {
}

type ExportLocationsInitParameters struct {
}

type ExportLocationsObservation struct {

	// Export path
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// Whether this is the preferred export location
	Preferred *bool `json:"preferred,omitempty" tf:"preferred,omitempty"`
}

type ExportLocationsParameters struct {
}

type FileShareCurrentStateInitParameters struct {
}

type FileShareCurrentStateLocationInitParameters struct {
}

type FileShareCurrentStateLocationObservation struct {

	// Availability zone
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// Region
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type FileShareCurrentStateLocationParameters struct {
}

type FileShareCurrentStateObservation struct {
	AccessRules []CurrentStateAccessRulesObservation `json:"accessRules,omitempty" tf:"access_rules,omitempty"`

	Capabilities []CapabilitiesObservation `json:"capabilities,omitempty" tf:"capabilities,omitempty"`

	// File share description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ExportLocations []ExportLocationsObservation `json:"exportLocations,omitempty" tf:"export_locations,omitempty"`

	Location *FileShareCurrentStateLocationObservation `json:"location,omitempty" tf:"location,omitempty"`

	// File share name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// File share protocol
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// ID of the share network the file share is attached to
	ShareNetworkID *string `json:"shareNetworkId,omitempty" tf:"share_network_id,omitempty"`

	// File share type
	ShareType *string `json:"shareType,omitempty" tf:"share_type,omitempty"`

	// Size of the file share in GB
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`
}

type FileShareCurrentStateParameters struct {
}

type FileShareInitParameters struct {
	AccessRules []AccessRulesInitParameters `json:"accessRules,omitempty" tf:"access_rules,omitempty"`

	// The availability zone where the file share will be created
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// File share description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// File share name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// File share protocol (`NFS`)
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// Region where the file share will be created
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Service name of the resource representing the id of the cloud project
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// ID of a pre-existing share network to attach the file share to
	// +crossplane:generate:reference:type=github.com/edixos/provider-ovh/apis/namespaced/storage/v1alpha1.FileShareNetwork
	ShareNetworkID *string `json:"shareNetworkId,omitempty" tf:"share_network_id,omitempty"`

	// Reference to a FileShareNetwork in storage to populate shareNetworkId.
	// +kubebuilder:validation:Optional
	ShareNetworkIDRef *v1.NamespacedReference `json:"shareNetworkIdRef,omitempty" tf:"-"`

	// Selector for a FileShareNetwork in storage to populate shareNetworkId.
	// +kubebuilder:validation:Optional
	ShareNetworkIDSelector *v1.NamespacedSelector `json:"shareNetworkIdSelector,omitempty" tf:"-"`

	// File share type (e.g. `STANDARD_1AZ`)
	ShareType *string `json:"shareType,omitempty" tf:"share_type,omitempty"`

	// Size of the file share in GB
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`
}

type FileShareObservation struct {
	AccessRules []AccessRulesObservation `json:"accessRules,omitempty" tf:"access_rules,omitempty"`

	// The availability zone where the file share will be created
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// Computed hash representing the current target specification value
	Checksum *string `json:"checksum,omitempty" tf:"checksum,omitempty"`

	// Creation date of the file share
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	CurrentState *FileShareCurrentStateObservation `json:"currentState,omitempty" tf:"current_state,omitempty"`

	// File share description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// File share name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// File share protocol (`NFS`)
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// Region where the file share will be created
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// File share readiness in the system (CREATING, DELETING, ERROR, OUT_OF_SYNC, READY, UPDATING)
	ResourceStatus *string `json:"resourceStatus,omitempty" tf:"resource_status,omitempty"`

	// Service name of the resource representing the id of the cloud project
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// ID of a pre-existing share network to attach the file share to
	ShareNetworkID *string `json:"shareNetworkId,omitempty" tf:"share_network_id,omitempty"`

	// File share type (e.g. `STANDARD_1AZ`)
	ShareType *string `json:"shareType,omitempty" tf:"share_type,omitempty"`

	// Size of the file share in GB
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// Last update date of the file share
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type FileShareParameters struct {

	// +kubebuilder:validation:Optional
	AccessRules []AccessRulesParameters `json:"accessRules,omitempty" tf:"access_rules,omitempty"`

	// The availability zone where the file share will be created
	// +kubebuilder:validation:Optional
	AvailabilityZone *string `json:"availabilityZone,omitempty" tf:"availability_zone,omitempty"`

	// File share description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// File share name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// File share protocol (`NFS`)
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// Region where the file share will be created
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Service name of the resource representing the id of the cloud project
	// +kubebuilder:validation:Optional
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`

	// ID of a pre-existing share network to attach the file share to
	// +crossplane:generate:reference:type=github.com/edixos/provider-ovh/apis/namespaced/storage/v1alpha1.FileShareNetwork
	// +kubebuilder:validation:Optional
	ShareNetworkID *string `json:"shareNetworkId,omitempty" tf:"share_network_id,omitempty"`

	// Reference to a FileShareNetwork in storage to populate shareNetworkId.
	// +kubebuilder:validation:Optional
	ShareNetworkIDRef *v1.NamespacedReference `json:"shareNetworkIdRef,omitempty" tf:"-"`

	// Selector for a FileShareNetwork in storage to populate shareNetworkId.
	// +kubebuilder:validation:Optional
	ShareNetworkIDSelector *v1.NamespacedSelector `json:"shareNetworkIdSelector,omitempty" tf:"-"`

	// File share type (e.g. `STANDARD_1AZ`)
	// +kubebuilder:validation:Optional
	ShareType *string `json:"shareType,omitempty" tf:"share_type,omitempty"`

	// Size of the file share in GB
	// +kubebuilder:validation:Optional
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`
}

// FileShareSpec defines the desired state of FileShare
type FileShareSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FileShareParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FileShareInitParameters `json:"initProvider,omitempty"`
}

// FileShareStatus defines the observed state of FileShare.
type FileShareStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FileShareObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FileShare is the Schema for the FileShares API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,ovh}
type FileShare struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.protocol) || (has(self.initProvider) && has(self.initProvider.protocol))",message="spec.forProvider.protocol is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceName) || (has(self.initProvider) && has(self.initProvider.serviceName))",message="spec.forProvider.serviceName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.shareType) || (has(self.initProvider) && has(self.initProvider.shareType))",message="spec.forProvider.shareType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.size) || (has(self.initProvider) && has(self.initProvider.size))",message="spec.forProvider.size is a required parameter"
	Spec   FileShareSpec   `json:"spec"`
	Status FileShareStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FileShareList contains a list of FileShares
type FileShareList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FileShare `json:"items"`
}

// Repository type metadata.
var (
	FileShare_Kind             = "FileShare"
	FileShare_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FileShare_Kind}.String()
	FileShare_KindAPIVersion   = FileShare_Kind + "." + CRDGroupVersion.String()
	FileShare_GroupVersionKind = CRDGroupVersion.WithKind(FileShare_Kind)
)

func init() {
	SchemeBuilder.Register(&FileShare{}, &FileShareList{})
}
