apiVersion: lb.ovh.edixos.io/v1alpha1
kind: Refresh
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/refresh
  labels:
    testing.upbound.io/example-name: mylb
  name: mylb
spec:
  forProvider:
    keepers:
    - ${ovh_iploadbalancing_tcp_farm_server.backend.*.address}
    serviceName: ${data.ovh_iploadbalancing.lb.service_name}

---

apiVersion: lb.ovh.edixos.io/v1alpha1
kind: TCPFarm
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/refresh
  labels:
    testing.upbound.io/example-name: farm_name
  name: farm-name
spec:
  forProvider:
    port: 8080
    serviceName: ${data.ovh_iploadbalancing.lb.service_name}
    zone: all

---

apiVersion: lb.ovh.edixos.io/v1alpha1
kind: TCPFarmServer
metadata:
  annotations:
    meta.upbound.io/example-id: lb/v1alpha1/refresh
  labels:
    testing.upbound.io/example-name: backend
  name: backend
spec:
  forProvider:
    address: 4.5.6.7
    backup: true
    displayName: mybackend
    farmId: ${ovh_iploadbalancing_tcp_farm.farm_name.id}
    port: 80
    probe: true
    proxyProtocolVersion: v2
    serviceName: ${data.ovh_iploadbalancing.lb.service_name}
    ssl: false
    status: active
    weight: 2
