# Project creation still not working, need to find out the root cause.
apiVersion: cloud.ovh.edixos.io/v1alpha1
kind: User
metadata:
  name: hello-edixos
spec:
  providerConfigRef:
    name: default
  forProvider:
    serviceName: 980cbcf06e6a4e6e8a91a7d125b26bba
  writeConnectionSecretToRef:
    name: user-credentials
    namespace: default