apiVersion: kube.ovh.edixos.io/v1alpha1
kind: NodePool
metadata:
  name: hello-edixos
spec:
  providerConfigRef:
    name: default
  forProvider:
    serviceName: 980cbcf06e6a4e6e8a91a7d125b26bba
    name: hello-crossplane
    flavorName: b2-7
    desiredNodes: 1
    maxNodes: 1
    minNodes: 1
    monthlyBilled: false
    kubeIdRef:
      name: hello-edixos