apiVersion: domain.ovh.edixos.io/v1alpha1
kind: ZoneImport
metadata:
  annotations:
    meta.upbound.io/example-id: domain/v1alpha1/zoneimport
  labels:
    testing.upbound.io/example-name: import
  name: import
spec:
  forProvider:
    zoneFile: ${file("./example.zone")}
    zoneName: mysite.ovh
