/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type IAMInitParameters struct {
}

type IAMObservation struct {

	// (String) Set the name displayed in Manager for this KMS
	// Resource display name
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (String) OKMS ID
	// Unique identifier of the resource
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Map of String) Resource tags. Tags that were internally computed are prefixed with ovh:
	// Resource tags. Tags that were internally computed are prefixed with ovh:
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) Unique resource name used in policies
	// Unique resource name used in policies
	Urn *string `json:"urn,omitempty" tf:"urn,omitempty"`
}

type IAMParameters struct {
}

type OkmsInitParameters struct {

	// (String) Set the name displayed in Manager for this KMS
	// Set the name displayed in Manager for this KMS
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (String) OVH subsidiary
	// OVH subsidiaries
	OvhSubsidiary *string `json:"ovhSubsidiary,omitempty" tf:"ovh_subsidiary,omitempty"`

	// (String) KMS region
	// KMS region
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type OkmsObservation struct {

	// (String) Set the name displayed in Manager for this KMS
	// Set the name displayed in Manager for this KMS
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Attributes) IAM resource metadata (see below for nested schema)
	IAM *IAMObservation `json:"iam,omitempty" tf:"iam,omitempty"`

	// (String) OKMS ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) KMS kmip API endpoint
	// KMS kmip API endpoint
	KmipEndpoint *string `json:"kmipEndpoint,omitempty" tf:"kmip_endpoint,omitempty"`

	// (String) OVH subsidiary
	// OVH subsidiaries
	OvhSubsidiary *string `json:"ovhSubsidiary,omitempty" tf:"ovh_subsidiary,omitempty"`

	// (String) KMS public CA (Certificate Authority)
	// KMS public CA (Certificate Authority)
	PublicCA *string `json:"publicCa,omitempty" tf:"public_ca,omitempty"`

	// (String) KMS region
	// KMS region
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) KMS rest API endpoint
	// KMS rest API endpoint
	RestEndpoint *string `json:"restEndpoint,omitempty" tf:"rest_endpoint,omitempty"`

	// (String) KMS rest API swagger UI
	// KMS rest API swagger UI
	SwaggerEndpoint *string `json:"swaggerEndpoint,omitempty" tf:"swagger_endpoint,omitempty"`
}

type OkmsParameters struct {

	// (String) Set the name displayed in Manager for this KMS
	// Set the name displayed in Manager for this KMS
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (String) OVH subsidiary
	// OVH subsidiaries
	// +kubebuilder:validation:Optional
	OvhSubsidiary *string `json:"ovhSubsidiary,omitempty" tf:"ovh_subsidiary,omitempty"`

	// (String) KMS region
	// KMS region
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

// OkmsSpec defines the desired state of Okms
type OkmsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     OkmsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OkmsInitParameters `json:"initProvider,omitempty"`
}

// OkmsStatus defines the observed state of Okms.
type OkmsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OkmsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Okms is the Schema for the Okmss API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,ovh}
type Okms struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ovhSubsidiary) || (has(self.initProvider) && has(self.initProvider.ovhSubsidiary))",message="spec.forProvider.ovhSubsidiary is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	Spec   OkmsSpec   `json:"spec"`
	Status OkmsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OkmsList contains a list of Okmss
type OkmsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Okms `json:"items"`
}

// Repository type metadata.
var (
	Okms_Kind             = "Okms"
	Okms_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Okms_Kind}.String()
	Okms_KindAPIVersion   = Okms_Kind + "." + CRDGroupVersion.String()
	Okms_GroupVersionKind = CRDGroupVersion.WithKind(Okms_Kind)
)

func init() {
	SchemeBuilder.Register(&Okms{}, &OkmsList{})
}
